# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bean',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='bean',
            name='strength',
        ),
        migrations.AddField(
            model_name='bean',
            name='price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bean',
            name='type',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bean',
            name='species',
            field=models.CharField(max_length=15),
        ),
    ]
