# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_auto_20170816_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bean',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
