# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_coffee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bean',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='extrainstructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='milk',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='powders',
            field=models.ManyToManyField(blank=True, to='coffee.Powder'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='shots',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='syrups',
            field=models.ManyToManyField(blank=True, to='coffee.Syrup'),
        ),
        migrations.AlterField(
            model_name='powder',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='roast',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='syrup',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
