# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_auto_20170820_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
    ]
