# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0009_auto_20170821_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='name',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
